package com.example.documentmanager;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;

@SuppressWarnings("serial")
public class DocEditor extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private TextArea html;
	@AutoGenerated
	private RichTextArea wysiwyg;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public DocEditor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	public void setPropertyDataSource(TextFileProperty doc) {
		html.setPropertyDataSource(doc);
		wysiwyg.setPropertyDataSource(doc);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1,
				"top:20.0px;right:29.0px;bottom:16.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// wysiwyg
		wysiwyg = new RichTextArea();
		wysiwyg.setImmediate(false);
		wysiwyg.setWidth("100.0%");
		wysiwyg.setHeight("100.0%");
		tabSheet_1.addTab(wysiwyg, "WYSIWYG", null);
		
		// html
		html = new TextArea();
		html.setImmediate(false);
		html.setWidth("100.0%");
		html.setHeight("100.0%");
		tabSheet_1.addTab(html, "HTML", null);
		
		return tabSheet_1;
	}

}
